### PR TITLE
DVB Reference Client - adds Chinese language

### PR DESCRIPTION
**Pull request by paulhiggs**
This Pull Request adds Chinese language support.
It also 'points' to a private backend deployment (at `paulhiggs.ddns.net:8118`) which needs not be merged.

### CODE REVIEW

**Comment by jpiesing** [comment]
@paulhiggs Would it be possible to split this into 2 pull requests, one including the pointer to your private backend and one including everything else? Would the result of merging everything **except** your deployment backend be coherent?

**Comment by paulhiggs** [comment]
Yes, i can really only test it on my home server, but can then revert out the home server stuff and make a commit

**Comment by paulhiggs** [comment]
I had thought that Sofia could just merge the parts that do not include my local hostname

**Comment by juhajoki** [comment]
sure, we can merge only the relevant commits.

**Comment by paulhiggs** [comment]
Here are two 'git format-patch` files to merge, one adds the "'build your own server' instructions" and the other is "Chinese localisation" - I though this might be easier then a merge from my overdeveloped fork.
[0001-Add-Chinese-localization.zip](https://github.com/DVBproject/DVB-I-Reference-Client/files/6521549/0001-Add-Chinese-localization.zip)
[0002-instructions-to-build-your-own-server.zip](https://github.com/DVBproject/DVB-I-Reference-Client/files/6521550/0002-instructions-to-build-your-own-server.zip)

**Comment by sofia-tsa** [comment]
The Chinese translation seems fine, atleast on the Android client. HbbTV client not so much but the HbbTV client translation implementation seems to be the issue, not the translation itself. I can take a look at that.

The slepr-master.xml contains direct links to the service list xml files INSTALL--LOCATION/backend/servicelists/example.xml but those service lists need to be processed by the localinstall.php so the service logos and content guide works. Also the localinstall.php has a security issue that you can get any file that the PHP user can read with a correct path. It depends on the server and PHP user settings but in normal system http://your.test.server/dvb-i-reference/backend/localinstall.php?list=/etc/resolv.conf would probably work.

**Comment by paulhiggs** [comment]
> The slepr-master.xml contains direct links to the service list xml files INSTALL--LOCATION/backend/servicelists/example.xml but those service lists need to be processed by the localinstall.php so the service logos and content guide works. Also the localinstall.php has a security issue that you can get any file that the PHP user can read with a correct path. It depends on the server and PHP user settings but in normal system http://your.test.server/dvb-i-reference/backend/localinstall.php?list=/etc/resolv.conf would probably work.

Here is an additional patch that removes the generalized `localinstal.php` replacing with `drm.xml.php` which only localizes `drm.xml`


[0003-PHP-wrapper-for-drm.xml-local-installation.zip](https://github.com/DVBproject/DVB-I-Reference-Client/files/6639328/0003-PHP-wrapper-for-drm.xml-local-installation.zip)

**Review by sofia-tsa — COMMENTED** [review]
Translations are fine. 
The local setup is fine but all the service lists in the service list registry need to work. 
So all the service lists need to be processed by the PHP or the local installation changes only applied to those service lists that are meant to be used with the local setup.

**Comment by paulhiggs** [comment]
> The local setup is fine but all the service lists in the service list registry need to work.
Some tests I made on my 'local copy' showed these to be working

> So all the service lists need to be processed by the PHP or the local installation changes only applied to those service lists that are meant to be used with the local setup.
Only service lists with 'local information' need to be processed with PHP, and this is only `drm.xml`. Service delivery is unchanged

**Comment by sofia-tsa** [comment]
Yes, but all the other local service lists have broken content guide and service logo links because the service provider list contains a direct link to the xml file,for example:
     <dvbisd:URI>INSTALL--LOCATION/backend/servicelists/example.xml</dvbisd:URI> 
and the example.xml service contains:
    <ScheduleInfoEndpoint contentType="application/xml">
      <URI>INSTALL--LOCATION/backend/schedule.php</URI>
    </ScheduleInfoEndpoint>
example.xml is not processed by the PHP and so the links are broken.

Would it be possible to fix the localinstallation.php/servicelist.php so that that all the local servicelists are processed by the PHP in a secure way. I could provide a patch with a fixed PHP and service provider list with those fixes. Or have the other servicelists in the provider list pointed to the github so they would be usable with the local installation also?

**Comment by sofia-tsa** [comment]
[0001-use-servicelist.php-to-process-local-servicelist-lin.patch.zip](https://github.com/DVBproject/DVB-I-Reference-Client/files/6647103/0001-use-servicelist.php-to-process-local-servicelist-lin.patch.zip)
Would this work?

**Comment by paulhiggs** [comment]
> [0001-use-servicelist.php-to-process-local-servicelist-lin.patch.zip](https://github.com/DVBproject/DVB-I-Reference-Client/files/6647103/0001-use-servicelist.php-to-process-local-servicelist-lin.patch.zip)
> Would this work?

Yes, this would also work. The key is that only files in the same directory are 'localized'. You could also add an "ends in `.xml`" test to ensure only instance documents are requested

**Comment by sofia-tsa** [comment]
Ok. I'll merge the pull request and add the changes, then I'll tag a release and update the stage installation

**Pull request merged**
